networks:
  dev:

volumes:
  db_data:
  semaphore_data:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: 192.168.0.60
      DB_PORT: 5432
      DB_USER: postgres 
      DB_PASS: qwerty
      DB_NAME: npis
    ports:
      - "8000:8000"
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    networks:
      - dev