---
- name: Create user + home (manual)
  hosts: test_debian
  become: true
  tags: always

  pre_tasks:
    - name: Guard vars
      ansible.builtin.assert:
        that:
          - user_name is defined
          - user_uid  is defined
          - user_home is defined
      tags: always

  tasks:
    - name: Add user
      ansible.builtin.user:
        name:  "{{ user_name }}"
        uid:   "{{ user_uid }}"
        home:  "{{ user_home }}"
        create_home: yes
        shell: /bin/bash
        state: present
      tags: [user, create]

    - name: Set home perms
      ansible.builtin.file:
        path: "{{ user_home }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0750"
      tags: [user, perms]
