- name: Add user with password
  hosts: test_debian
  become: true
  tags:
    - deb

  tasks:
    - name: Add user '{{ example_user }}' with UID and password
      ansible.builtin.user:
        name: "{{ example_user }}"
        uid: "{{ example_uid }}"
        comment: "Example User"
        home: "{{ example_home }}"
        create_home: yes
        shell: /bin/bash
        password: "{{ example_password_hash }}"
        update_password: always
        password_lock: no
