---
- name: Add user w/ hashed password (manual)
  hosts: test_debian
  become: true
  tags: always
  
  pre_tasks:
    - ansible.builtin.assert:
        that:
          - example_user          is defined
          - example_uid           is defined
          - example_home          is defined
          - example_password_hash is defined

  tasks:
    - name: Create user
      ansible.builtin.user:
        name:     "{{ example_user }}"
        uid:      "{{ example_uid }}"
        home:     "{{ example_home }}"
        password: "{{ example_password_hash }}"
        update_password: always
        shell: /bin/bash
        create_home: yes
        state: present
      tags: [user, passwd, create]
