---
- name: Install Apache (manual)
  hosts: "{{ target_hosts | default('managed_hosts') }}"
  become: true

  pre_tasks:
    - ansible.builtin.assert:
        that: package_name is defined
      tags: always

  tasks:
    - name: Install apache
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: present
      tags: [apache, install]

    - name: Enable service
      ansible.builtin.service:
        name: "{{ package_name }}"
        state: started
        enabled: yes
      tags: [apache, service]
