---
- name: Ping hosts (no vars needed)
  hosts: "{{ target_hosts | default('managed_hosts') }}"
  gather_facts: false

  tasks:
    - name: Ping
      ansible.builtin.ping:
      tags: [ping, connectivity]
