---
- name: Security upgrades (no vars)
  hosts: test_debian
  become: true

  tasks:
    - name: Apt cache update
      ansible.builtin.apt:
        update_cache: yes
      tags: [apt, cache]

    - name: Apply security updates
      ansible.builtin.apt:
        upgrade: dist
        only_upgrade: yes
      tags: [apt, security]
