---
- name: SSH hardening (manual)
  hosts: "{{ target_host }}"
  become: true
  tags: always

  pre_tasks:
    - ansible.builtin.assert:
        that:
          - permit_root is defined
      tags: always

  vars:
    sshd_config_path: /etc/ssh/sshd_config

  tasks:
    - name: PermitRootLogin
      ansible.builtin.lineinfile:
        path: "{{ sshd_config_path }}"
        regexp: '^#?PermitRootLogin'
        line:  "PermitRootLogin {{ permit_root }}"
      notify: restart ssh
      tags: [ssh, root]

  handlers:
    - name: restart ssh
      ansible.builtin.service:
        name: "{{ ssh_service | default('ssh') }}"
        state: restarted
      tags: [ssh, service]
