---
- name: Configure UFW (manual)
  hosts: "{{ target_host }}"
  become: true
  tags: always

  tasks:
    - name: Install ufw
      ansible.builtin.apt:
        name: ufw
        state: present
      tags: [ufw, install]

    - name: Default policy deny
      community.general.ufw:
        state: enabled
        policy: "{{ ufw_default_policy | default('deny') }}"
      tags: [ufw, policy]
