---
- name: Deploy vulnerable Flink traversal for CVE-2020-17519
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    image: "vulhub/flink:1.11.2"
    container_name: "cve-2020-17519"

  tasks:
    - name: Pull vulnerable Flink image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Run vulnerable Flink container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        published_ports:
          - "8093:8081"
        state: started
        detach: true
