---
- name: Deploy vulnerable Flink JobManager for CVE-2020-13942
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    image: "vulhub/flink:2020-13942"
    container_name: "cve-2020-13942"

  tasks:
    - name: Pull vulnerable Flink image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Run vulnerable Flink container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        published_ports:
          - "8087:8081"
        state: started
        detach: true
