---
- name: Deploy vulnerable PHP-FPM for CVE-2019-11043
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    image: "vulhub/php-fpm-nginx:2019-11043"
    container_name: "cve-2019-11043"

  tasks:
    - name: Pull vulnerable PHP-FPM image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Run vulnerable PHP-FPM container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        published_ports:
          - "8086:80"
        state: started
        detach: true
