---
- name: Deploy vulnerable Druid for CVE-2021-25646
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    image: "vulhub/druid:2021-25646"
    container_name: "cve-2021-25646"

  tasks:
    - name: Pull vulnerable Druid image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Run vulnerable Druid container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        published_ports:
          - "8091:8888"
          - "8092:8081"
        state: started
        detach: true
