---
- name: Deploy vulnerable Struts2 S2-057 for CVE-2018-11776
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    image: "vulhub/struts2-s2-057:latest"
    container_name: "cve-2018-11776"

  tasks:
    - name: Pull vulnerable Struts2 image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Run vulnerable Struts2 container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        published_ports:
          - "8084:8080"
        state: started
        detach: true
