---
- name: Deploy vulnerable Flink JobManager for CVE-2020-13942
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    image: "vulhub/unomi:1.5.1"
    container_name: "cve-2020-13942"

  tasks:
  - name: Pull vulnerable Unomi image
    community.docker.docker_image:
      name: "{{ image }}"
      source: pull

  - name: Run Unomi (ports 8181/9443)
    community.docker.docker_container:
      name: "{{ container_name }}"
      image: "{{ image }}"
      published_ports:
        - "8087:8181"
        - "9443:9443"
      state: started
      detach: true
