---
- name: Deploy vulnerable PHP-FPM CVE-2019-11043
  hosts: "{{ target_host }}"
  gather_facts: false
  become: true

  vars:
    php_image: "php:7.2.10-fpm"
    nginx_image: "nginx:1.19.2-alpine"
    php_container: "cve-2019-11043-php"
    nginx_container: "cve-2019-11043-nginx"
    web_root: "/opt/cve-2019-11043/www"     
    nginx_conf: "/opt/cve-2019-11043/default.conf"

  tasks:
    - name: Pull images
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - "{{ php_image }}"
        - "{{ nginx_image }}"

    - name: Create network
      community.docker.docker_network:
        name: cve-2019-11043-net

    - name: Run PHP-FPM container
      community.docker.docker_container:
        name: "{{ php_container }}"
        image: "{{ php_image }}"
        networks:
          - name: cve-2019-11043-net
        volumes:
          - "{{ web_root }}:/var/www/html"
        state: started
        detach: true

    - name: Run nginx container
      community.docker.docker_container:
        name: "{{ nginx_container }}"
        image: "{{ nginx_image }}"
        networks:
          - name: cve-2019-11043-net
        volumes:
          - "{{ web_root }}:/usr/share/nginx/html"
          - "{{ nginx_conf }}:/etc/nginx/conf.d/default.conf"
        published_ports:
          - "8086:80"
        state: started
        detach: true
