---
- name: Deploy vulnerable ActiveMQ for CVE-2023-46604
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    image: "vulhub/activemq:5.15.9-2023-46604"
    container_name: "cve-2023-46604"

  tasks:
    - name: Pull vulnerable ActiveMQ image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Run vulnerable ActiveMQ container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        published_ports:
          - "61616:61616"
          - "8161:8161"
        state: started
        detach: true
