---
- name: Deploy vulnerable Spring Cloud Function for CVE-2022-22963
  hosts: "{{ target_host }}"
  gather_facts: false
  become: true

  vars:
    image: "vulhub/spring-cloud:2022-22963"
    container_name: "cve-2022-22963"

  tasks:
    - name: Pull vulnerable Spring Cloud Function image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Run vulnerable Spring Cloud Function container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        published_ports:
          - "8083:8080"
        state: started
        detach: true
