---
- name: Deploy vulnerable Grafana for CVE-2021-43798
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    image: "vulhub/grafana:8.3.0"
    container_name: "cve-2021-43798"

  tasks:
    - name: Pull vulnerable Grafana image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Run vulnerable Grafana container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        published_ports:
          - "3000:3000"
        env:
          GF_SECURITY_ADMIN_PASSWORD: "admin"
        state: started
        detach: true
