---
- name: Deploy vulnerable polkit for CVE-2021-4034
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    image: "vulhub/polkit:0.105"
    container_name: "cve-2021-4034"

  tasks:
    - name: Pull vulnerable polkit image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Run vulnerable polkit container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        command: ["sleep", "infinity"]
        tty: true
        auto_remove: false
        state: started
